### PR TITLE
Some fixes and improved flexibility

### PR DESCRIPTION
**Pull request by ehbello**
This PR addresses issues of hard-coded references, fixes argument handling, and also fixes minor inconsistencies in test configuration, enhancing the overall quality and flexibility of the project's automation workflows

### Key Changes:

1. **action.yml & docker.yml:**

    - Replaced all hard-coded references to andy5995 with `${{ github.repository_owner }}`, allowing the repository owner to be dynamically set based on the context. This change makes the workflows more portable and adaptable across forks.

2. **test.yml:**

    - Updated the tag reference from `rmw-0.9.2` to `v0.9.2`, fixing a potential error in repository versioning for tests.

    - Enhanced input argument testing by adding `--compression=xz` alongside `--no-sign`, which broadens the scope of test cases to include multiple parameters.

3. **entrypoint.sh:**

    - Updated the handling of `INPUT_ARGS` to accept more than one parameter, fixing flexibility for input arguments.

    - Modified file movement logic to support any tar extension `(tar.*)`, providing compatibility for different tar formats.

These modifications improve the reusability and flexibility of workflows, enhance testing robustness, and allow more versatile input handling in scripts.

### Testing & Validation:
Each change has been tested to ensure compatibility with the current repository structure and settings.

### CODE REVIEW

**Comment by andy5995** [comment]
Thank you.

> Each change has been tested to ensure compatibility with the current repository structure and settings.

How did you test them?

**Comment by ehbello** [comment]
> Thank you.
> 
> > Each change has been tested to ensure compatibility with the current repository structure and settings.
> 
> How did you test them?

Enabling Actions in my repository, passing related workflows and using the output artifacts as if they were coming from yours.

https://github.com/ehbello/gh-action-build-deb/actions/runs/11620406480
https://github.com/ehbello/gh-action-build-deb/actions/runs/11620406451

**Comment by andy5995** [comment]
@ehbello as you noticed, the changes can't be properly tested unless the docker image is updated with the changes you made to entrypoint.sh. I opened #8 to help with this in the future. If you're interested, we can figure that out after this is merged.

**Review by andy5995 — APPROVED** [review]

**Comment by andy5995** [comment]
@ehbello I'll just need to re-run the `test` action after the new image is built, but I think we'll be all good.

**Comment by ehbello** [comment]
> @ehbello as you noticed, the changes can't be properly tested unless the docker image is updated with the changes you made to entrypoint.sh. I opened #8 to help with this in the future. If you're interested, we can figure that out after this is merged.

Yep, I was working on it, but I need more time 😄

**Comment by andy5995** [comment]
Great!

ehbello Also, it's typically easier to make a branch on your fork for changes. That makes it easier to sync your fork with the upstream (upstream/original repo) in the future. See https://docs.github.com/en/get-started/using-github/github-flow#create-a-branch for more info.

Let me know if you need help syncing your fork. Most likely you will need to force-push to your `trunk` branch to reset back to https://github.com/andy5995/gh-action-build-deb/commit/5e5c37e249550f78bef5cfa90c101b2c65aabadc on the upstream. While you typically want to avoid force-pushing to the main branch, force-pushing to a main branch isn't anything to worry about in my opinion. If something gets screwed up, it's usually not difficult to get your fork main branch synced to the upstream main branch.

**Pull request merged**
